/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';


export interface ProductHeaderProps {
  className?: any;
}
export interface SeeAllProps {
  className?: any;
}
const SeeAll1: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `31px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const SeeAll2: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `700`,
  fontSize: `17.33333396911621px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `25.037036895751953px`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `2px`,
});

const Ellipse54: any = styled('img')({
  height: `30px`,
  width: `30px`,
  position: `absolute`,
  left: `129px`,
  top: `0px`,
});

const Ellipse55: any = styled('img')({
  height: `30px`,
  width: `30px`,
  position: `absolute`,
  left: `90px`,
  top: `1px`,
});

const Vector: any = styled('img')({
  height: `15px`,
  width: `15px`,
  position: `absolute`,
  left: `137px`,
  top: `8px`,
});

const Vector1: any = styled('img')({
  height: `15px`,
  width: `15px`,
  position: `absolute`,
  left: `128px`,
  top: `39px`,
});

function SeeAll(props: SeeAllProps): JSX.Element {
  return (
    <SeeAll1 className={props.className}>
      <SeeAll2>{`See all`}</SeeAll2>
      <Ellipse54
        src={`assets/images/SeeAll_Ellipse_54.png`}
        loading="lazy"
        alt={'Ellipse 54'}
      />
      <Ellipse55
        src={`assets/images/SeeAll_Ellipse_55.png`}
        loading="lazy"
        alt={'Ellipse 55'}
      />
      <Vector
        src={`assets/images/SeeAll_Vector.png`}
        loading="lazy"
        alt={'Vector'}
      />
      <Vector1
        src={`assets/images/SeeAll_Vector_1.png`}
        loading="lazy"
        alt={'Vector'}
      />
    </SeeAll1>
  );
}


const ProductHeader1: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `55px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const PopularNearYouSpan1: any = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `36px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `34px`,
  textTransform: `none`,
});

const PopularNearYouSpan2: any = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 107, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `36px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `34px`,
  textTransform: `none`,
});

const PopularNearYouSpan3: any = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `700`,
  fontSize: `36px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `34px`,
  textTransform: `none`,
});

const PopularNearYouSpan4: any = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 107, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `36px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `34px`,
  textTransform: `none`,
});

const PopularNearYouSpan5: any = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `36px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `34px`,
  textTransform: `none`,
});

const PopularNearYou: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: 'unset',
  fontWeight: `400`,
  fontSize: `36px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `34px`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const SeeAllMain: any = styled(SeeAll)(({ theme }: any) => ({
  width: `159px`,
  height: `31px`,
  position: `absolute`,
  left: `1082px`,
  top: `24px`,
}));

function ProductHeader(props: ProductHeaderProps): JSX.Element {
  return (
    <ProductHeader1 className={props.className}>
      <PopularNearYou>
        <PopularNearYouSpan1>{`Popular`}</PopularNearYouSpan1>
        <PopularNearYouSpan2>{` `}</PopularNearYouSpan2>
        <PopularNearYouSpan3>{`near`}</PopularNearYouSpan3>
        <PopularNearYouSpan4>{` `}</PopularNearYouSpan4>
        <PopularNearYouSpan5>{`you`}</PopularNearYouSpan5>
      </PopularNearYou>
      <SeeAllMain />
    </ProductHeader1>
  );
}

export default ProductHeader;
