/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import { FaCheck, FaTimes, FaArrowRight } from 'react-icons/fa';

export interface Component7Props {
  className?: any;
}

const Component71: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `51px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  paddingLeft: `20px`,
  paddingRight: `20px`,
  boxSizing: `border-box`,
});


const GreenBox: any = styled('div')({
  backgroundColor: `rgba(255, 251, 251, 1)`,
  border: `1px solid rgba(26, 206, 10, 1)`,
  boxSizing: `border-box`,
  borderRadius: `11px`,
  width: `101px`,
  height: `50px`,
  display: 'flex',
  justifyContent: 'space-around',
  alignContent: 'end',
});

const RedBox: any = styled('div')({
  backgroundColor: `rgba(255, 251, 251, 1)`,
  border: `1px solid rgba(255, 107, 0, 1)`,
  boxSizing: `border-box`,
  borderRadius: `11px`,
  width: `101px`,
  height: `50px`,
  display: 'flex',
  justifyContent: 'space-around',
  alignContent: 'center',

});

const Q12: any = styled('div')({
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(26, 206, 10, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,

});

const DirectionContainer: any = styled('div')({
  boxShadow: `0px 4px 50px rgba(0, 0, 0, 0.1)`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `49.57px`,
  height: `50px`,
  left: `1058px`,
  top: `0px`,
});

const Vector: any = styled('img')({
  height: `18.75px`,
  width: `21.24px`,
  position: `absolute`,
  left: `14px`,
  top: `16px`,
});

const Group343: any = styled('img')({
  height: `50px`,
  width: `49.57px`,
  position: `absolute`,
  left: `99px`,
  top: `100px`,
});

function Component7(props: Component7Props): JSX.Element {
  return (
    <Component71 className={props.className}>

      <GreenBox className="p-3 mr-3">
        <FaCheck />
        <Q12>{`#12`}</Q12>
      </GreenBox>
      <RedBox className="p-3">
        <FaTimes size={20} />
        <Q12>{`#12`}</Q12>
      </RedBox>
      <DirectionContainer>
        <Vector
          src={`assets/images/Component7_Vector.png`}
          loading="lazy"
          alt={'Vector'}
        />
      </DirectionContainer>
      <Group343
        src={`assets/images/Component7_Group_343.png`}
        loading="lazy"
        alt={'Group 343'}
      />
    </Component71>
  );
}

export default Component7;
