/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
export interface TrackingProps {
  className?: any;
}
const Tracking1: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `1058px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Rectangle1445: any = styled('div')({
  backgroundColor: `rgba(147, 147, 147, 1)`,
  width: `3px`,
  height: `428px`,
  position: `absolute`,
  left: `42px`,
  top: `592px`,
});

const Rectangle1444: any = styled('div')({
  backgroundColor: `rgba(255, 107, 0, 1)`,
  width: `3px`,
  height: `428px`,
  position: `absolute`,
  left: `42px`,
  top: `491px`,
});

const DeliveryDetails: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `30px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `34px`,
  textTransform: `none`,
  position: `absolute`,
  left: `12px`,
  top: `374px`,
});

const HayesValleys: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `25px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `34px`,
  textTransform: `none`,
  position: `absolute`,
  left: `89px`,
  top: `452px`,
});

const MesaNewJersey459431: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(93, 91, 91, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `23px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `34px`,
  textTransform: `none`,
  position: `absolute`,
  left: `90px`,
  top: `489px`,
});

const OrderRecieved: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `25px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `34px`,
  textTransform: `none`,
  position: `absolute`,
  left: `89px`,
  top: `582px`,
});

const RecivedBy: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(93, 91, 91, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `23px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `34px`,
  textTransform: `none`,
  position: `absolute`,
  left: `90px`,
  top: `619px`,
});

const OrderPickedUp: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `25px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `34px`,
  textTransform: `none`,
  position: `absolute`,
  left: `89px`,
  top: `793px`,
});

const YourOrderIsAlreadyPi: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(93, 91, 91, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `23px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `34px`,
  textTransform: `none`,
  position: `absolute`,
  left: `90px`,
  top: `830px`,
});

const OrderIsOnDelivery: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `25px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `34px`,
  textTransform: `none`,
  position: `absolute`,
  left: `89px`,
  top: `893px`,
});

const YourOrderIsOnDeliver: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(93, 91, 91, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `23px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `34px`,
  textTransform: `none`,
  position: `absolute`,
  left: `90px`,
  top: `929px`,
});

const Home: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `25px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `34px`,
  textTransform: `none`,
  position: `absolute`,
  left: `89px`,
  top: `988px`,
});

const RanchviewCalifornia1: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(93, 91, 91, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `23px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `34px`,
  textTransform: `none`,
  position: `absolute`,
  left: `89px`,
  top: `1024px`,
});

const MarkBrown: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `23px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `34px`,
  textTransform: `none`,
  position: `absolute`,
  left: `203px`,
  top: `687px`,
});

const Q32Do521: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(93, 91, 91, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `23px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `34px`,
  textTransform: `none`,
  position: `absolute`,
  left: `203px`,
  top: `726px`,
});

const Rectangle13: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `2px solid rgba(255, 107, 0, 1)`,
  boxSizing: `border-box`,
  borderRadius: `18px`,
  width: `999px`,
  height: `325px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const MaskGroup: any = styled('img')({
  height: `321.19px`,
  width: `992.04px`,
  position: `absolute`,
  left: `3px`,
  top: `2px`,
});

const Rectangle1443: any = styled('div')({
  backgroundColor: `rgba(255, 107, 0, 1)`,
  borderRadius: `11px`,
  width: `50px`,
  height: `50px`,
  position: `absolute`,
  left: `18px`,
  top: `452px`,
});

const Location: any = styled('img')({
  height: `32px`,
  width: `32px`,
  objectFit: `contain`,
  position: `absolute`,
  left: `27px`,
  top: `461px`,
});

const Ellipse62: any = styled('img')({
  height: `22px`,
  width: `22px`,
  position: `absolute`,
  left: `32px`,
  top: `591px`,
});

const Ellipse63: any = styled('img')({
  height: `22px`,
  width: `22px`,
  position: `absolute`,
  left: `32px`,
  top: `799px`,
});

const Ellipse64: any = styled('img')({
  height: `22px`,
  width: `22px`,
  position: `absolute`,
  left: `32px`,
  top: `902px`,
});

const MaskGroup1: any = styled('img')({
  height: `80px`,
  width: `80px`,
  position: `absolute`,
  left: `89px`,
  top: `683px`,
});

const CheckedCheckbox: any = styled('img')({
  height: `50px`,
  width: `50px`,
  objectFit: `contain`,
  position: `absolute`,
  left: `20px`,
  top: `991px`,
});

const Phone: any = styled('img')({
  height: `50px`,
  width: `50px`,
  objectFit: `contain`,
  position: `absolute`,
  left: `738px`,
  top: `705px`,
});

const Envelope: any = styled('img')({
  height: `50px`,
  width: `50px`,
  objectFit: `contain`,
  position: `absolute`,
  left: `849px`,
  top: `705px`,
});

function Tracking(props: TrackingProps): JSX.Element {
  return (
    <Tracking1 className={props.className}>
      <Rectangle1445></Rectangle1445>
      <Rectangle1444></Rectangle1444>
      <DeliveryDetails>{`Delivery Details `}</DeliveryDetails>
      <HayesValleys>{`Hayes Valleys `}</HayesValleys>
      <MesaNewJersey459431>{`Mesa, New Jersey 459431`}</MesaNewJersey459431>
      <OrderRecieved>{`Order Recieved`}</OrderRecieved>
      <RecivedBy>{`Recived by`}</RecivedBy>
      <OrderPickedUp>{`Order Picked Up`}</OrderPickedUp>
      <YourOrderIsAlreadyPi>
        {`Your order is already picked up`}
      </YourOrderIsAlreadyPi>
      <OrderIsOnDelivery>{`Order is on Delivery`}</OrderIsOnDelivery>
      <YourOrderIsOnDeliver>
        {`Your order is on delivery, will arrive in 5-10min`}
      </YourOrderIsOnDeliver>
      <Home>{`Home`}</Home>
      <RanchviewCalifornia1>
        {`Ranchview, California 123459`}
      </RanchviewCalifornia1>
      <MarkBrown>{`Mark brown`}</MarkBrown>
      <Q32Do521>{`32DO521`}</Q32Do521>
      <Rectangle13></Rectangle13>
      <MaskGroup
        src={`assets/images/Tracking_Mask_group.png`}
        loading="lazy"
        alt={'Mask group'}
      />
      <Rectangle1443></Rectangle1443>
      <Location
        src={`assets/images/Tracking_Location.png`}
        loading="lazy"
        alt={'Location'}
      />
      <Ellipse62
        src={`assets/images/Tracking_Ellipse_62.png`}
        loading="lazy"
        alt={'Ellipse 62'}
      />
      <Ellipse63
        src={`assets/images/Tracking_Ellipse_63.png`}
        loading="lazy"
        alt={'Ellipse 63'}
      />
      <Ellipse64
        src={`assets/images/Tracking_Ellipse_64.png`}
        loading="lazy"
        alt={'Ellipse 64'}
      />
      <MaskGroup1
        src={`assets/images/Tracking_Mask_group_1.png`}
        loading="lazy"
        alt={'Mask group'}
      />
      <CheckedCheckbox
        src={`assets/images/Tracking_Checked_Checkbox.png`}
        loading="lazy"
        alt={'Checked Checkbox'}
      />
      <Phone
        src={`assets/images/Tracking_Phone.png`}
        loading="lazy"
        alt={'Phone'}
      />
      <Envelope
        src={`assets/images/Tracking_Envelope.png`}
        loading="lazy"
        alt={'Envelope'}
      />
    </Tracking1>
  );
}

export default Tracking;
