/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';

export interface OrderBoxProps {
  className?: any;
}

const OrderBox1: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `411px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const OrderBox2: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  boxShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  border: `1px solid rgba(138, 138, 138, 1)`,
  boxSizing: `border-box`,
  borderRadius: `9px`,
  width: `341px`,
  height: `411px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

function OrderBox(props: OrderBoxProps): JSX.Element {
  return (
    <OrderBox1 className={props.className}>
      <OrderBox2></OrderBox2>
    </OrderBox1>
  );
}

export default OrderBox;
