/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import OrderBox from '../OrderBox/OrderBox';
import Component7 from '../Component7/Component7';

export interface OrderList {
  className?: any;
}

const Component81: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `938px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const OrderBox1: any = styled(OrderBox)(({ theme }: any) => ({
  width: `341px`,
  height: `411px`,
  position: `absolute`,
  left: `27px`,
  top: `91px`,
}));

const OrderPlaced1: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `300px`,
  height: `374px`,
  left: `46px`,
  top: `111px`,
});

const Order10: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Q17May20230530Pm: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(121, 123, 126, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `27px`,
});

const Rectangle17: any = styled('div')({
  border: `1px solid rgba(26, 206, 10, 1)`,
  boxSizing: `border-box`,
  borderRadius: `25px`,
  width: `130px`,
  height: `50px`,
  position: `absolute`,
  left: `170px`,
  top: `324px`,
});

const Completed: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(26, 206, 10, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `211px`,
  top: `341px`,
});

const Vector10: any = styled('img')({
  height: `10px`,
  width: `16px`,
  position: `absolute`,
  left: `185px`,
  top: `343px`,
});

const ChickenBbq: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `100px`,
  top: `82px`,
});

const WithExtraChesse: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(121, 123, 126, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `99px`,
  top: `109px`,
});

const Q20: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `101px`,
  top: `136px`,
});

const Qty1: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `260px`,
  top: `134px`,
});

const Line33: any = styled('div')({
  border: `1px solid rgba(227, 227, 227, 1)`,
  width: `294px`,
  height: `0px`,
  position: `absolute`,
  left: `4px`,
  top: `300px`,
});

const Image3: any = styled('img')({
  height: `49px`,
  width: `50px`,
  position: `absolute`,
  left: `249px`,
  top: `0px`,
});

const ChickenBbq1: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `146px`,
  top: `310px`,
});

const WithExtraChesse1: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(121, 123, 126, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `145px`,
  top: `337px`,
});

const Q201: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `147px`,
  top: `364px`,
});

const Qty11: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `306px`,
  top: `362px`,
});

const MaskGroup: any = styled('img')({
  height: `80px`,
  width: `80px`,
  position: `absolute`,
  left: `46px`,
  top: `187px`,
});

const MaskGroup1: any = styled('img')({
  height: `80px`,
  width: `80px`,
  position: `absolute`,
  left: `46px`,
  top: `312px`,
});

const Qty12: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `964px`,
  top: `362px`,
});

const Group1719: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `341px`,
  height: `411px`,
  left: `766px`,
  top: `91px`,
});

const OrderBox2: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(138, 138, 138, 1)`,
  boxSizing: `border-box`,
  borderRadius: `9px`,
  width: `341px`,
  height: `411px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const OrderPlaced11: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `300px`,
  height: `374px`,
  left: `19px`,
  top: `20px`,
});

const Order12: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Q17May20230530Pm1: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(121, 123, 126, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `27px`,
});

const Rectangle171: any = styled('div')({
  border: `1px solid rgba(26, 206, 10, 1)`,
  boxSizing: `border-box`,
  borderRadius: `25px`,
  width: `130px`,
  height: `50px`,
  position: `absolute`,
  left: `170px`,
  top: `324px`,
});

const Completed1: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(26, 206, 10, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `211px`,
  top: `341px`,
});

const Vector101: any = styled('img')({
  height: `10px`,
  width: `16px`,
  position: `absolute`,
  left: `185px`,
  top: `343px`,
});

const ChickenBbq2: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `100px`,
  top: `82px`,
});

const WithExtraChesse2: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(121, 123, 126, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `99px`,
  top: `109px`,
});

const Q202: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `101px`,
  top: `136px`,
});

const Qty13: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `260px`,
  top: `134px`,
});

const Qty14: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `260px`,
  top: `253px`,
});

const Line331: any = styled('div')({
  border: `1px solid rgba(227, 227, 227, 1)`,
  width: `294px`,
  height: `0px`,
  position: `absolute`,
  left: `4px`,
  top: `300px`,
});

const Image31: any = styled('img')({
  height: `49px`,
  width: `50px`,
  position: `absolute`,
  left: `249px`,
  top: `0px`,
});

const ChickenBbq3: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `119px`,
  top: `219px`,
});

const WithExtraChesse3: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(121, 123, 126, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `118px`,
  top: `246px`,
});

const Q203: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `120px`,
  top: `273px`,
});

const MaskGroup2: any = styled('img')({
  height: `80px`,
  width: `80px`,
  position: `absolute`,
  left: `19px`,
  top: `96px`,
});

const MaskGroup3: any = styled('img')({
  height: `80px`,
  width: `80px`,
  position: `absolute`,
  left: `19px`,
  top: `221px`,
});

const Group1720: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `341px`,
  height: `411px`,
  left: `27px`,
  top: `527px`,
});

const OrderBox3: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(138, 138, 138, 1)`,
  boxSizing: `border-box`,
  borderRadius: `9px`,
  width: `341px`,
  height: `411px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const OrderPlaced12: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `300px`,
  height: `374px`,
  left: `19px`,
  top: `20px`,
});

const Order13: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Q17May20230530Pm2: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(121, 123, 126, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `27px`,
});

const Rectangle172: any = styled('div')({
  border: `1px solid rgba(26, 206, 10, 1)`,
  boxSizing: `border-box`,
  borderRadius: `25px`,
  width: `130px`,
  height: `50px`,
  position: `absolute`,
  left: `170px`,
  top: `324px`,
});

const Completed2: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(26, 206, 10, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `211px`,
  top: `341px`,
});

const Vector102: any = styled('img')({
  height: `10px`,
  width: `16px`,
  position: `absolute`,
  left: `185px`,
  top: `343px`,
});

const ChickenBbq4: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `100px`,
  top: `82px`,
});

const WithExtraChesse4: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(121, 123, 126, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `99px`,
  top: `109px`,
});

const Q204: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `101px`,
  top: `136px`,
});

const Qty15: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `260px`,
  top: `134px`,
});

const Line332: any = styled('div')({
  border: `1px solid rgba(227, 227, 227, 1)`,
  width: `294px`,
  height: `0px`,
  position: `absolute`,
  left: `4px`,
  top: `300px`,
});

const Image32: any = styled('img')({
  height: `49px`,
  width: `50px`,
  position: `absolute`,
  left: `249px`,
  top: `0px`,
});

const ChickenBbq5: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `119px`,
  top: `219px`,
});

const WithExtraChesse5: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(121, 123, 126, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `118px`,
  top: `246px`,
});

const Q205: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `120px`,
  top: `273px`,
});

const MaskGroup4: any = styled('img')({
  height: `80px`,
  width: `80px`,
  position: `absolute`,
  left: `19px`,
  top: `96px`,
});

const MaskGroup5: any = styled('img')({
  height: `80px`,
  width: `80px`,
  position: `absolute`,
  left: `19px`,
  top: `221px`,
});

const Group1721: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `341px`,
  height: `411px`,
  left: `397px`,
  top: `527px`,
});

const OrderBox4: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(138, 138, 138, 1)`,
  boxSizing: `border-box`,
  borderRadius: `9px`,
  width: `341px`,
  height: `411px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const OrderPlaced13: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `299px`,
  height: `300px`,
  left: `19px`,
  top: `20px`,
});

const Order14: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Q17May20230530Pm3: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(121, 123, 126, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `27px`,
});

const ChickenBbq6: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `100px`,
  top: `82px`,
});

const WithExtraChesse6: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(121, 123, 126, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `99px`,
  top: `109px`,
});

const Q206: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `101px`,
  top: `136px`,
});

const Qty16: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `260px`,
  top: `134px`,
});

const Line333: any = styled('div')({
  border: `1px solid rgba(227, 227, 227, 1)`,
  width: `294px`,
  height: `0px`,
  position: `absolute`,
  left: `4px`,
  top: `300px`,
});

const Image33: any = styled('img')({
  height: `49px`,
  width: `50px`,
  position: `absolute`,
  left: `249px`,
  top: `0px`,
});

const ChickenBbq7: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `119px`,
  top: `219px`,
});

const WithExtraChesse7: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(121, 123, 126, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `118px`,
  top: `246px`,
});

const Q207: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `120px`,
  top: `273px`,
});

const MaskGroup6: any = styled('img')({
  height: `80px`,
  width: `80px`,
  position: `absolute`,
  left: `19px`,
  top: `96px`,
});

const MaskGroup7: any = styled('img')({
  height: `80px`,
  width: `80px`,
  position: `absolute`,
  left: `19px`,
  top: `221px`,
});

const Qty17: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `306px`,
  top: `797px`,
});

const Qty18: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `676px`,
  top: `797px`,
});

const Group1722: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `341px`,
  height: `411px`,
  left: `767px`,
  top: `527px`,
});

const OrderBox5: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(138, 138, 138, 1)`,
  boxSizing: `border-box`,
  borderRadius: `9px`,
  width: `341px`,
  height: `411px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const OrderPlaced14: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `300px`,
  height: `374px`,
  left: `19px`,
  top: `20px`,
});

const Order15: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Q17May20230530Pm4: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(121, 123, 126, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `27px`,
});

const Rectangle173: any = styled('div')({
  border: `1px solid rgba(26, 206, 10, 1)`,
  boxSizing: `border-box`,
  borderRadius: `25px`,
  width: `130px`,
  height: `50px`,
  position: `absolute`,
  left: `170px`,
  top: `324px`,
});

const Completed3: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(26, 206, 10, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `211px`,
  top: `341px`,
});

const Vector103: any = styled('img')({
  height: `10px`,
  width: `16px`,
  position: `absolute`,
  left: `185px`,
  top: `343px`,
});

const ChickenBbq8: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `100px`,
  top: `82px`,
});

const WithExtraChesse8: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(121, 123, 126, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `99px`,
  top: `109px`,
});

const Q208: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `101px`,
  top: `136px`,
});

const Qty19: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `260px`,
  top: `134px`,
});

const Qty110: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `260px`,
  top: `251px`,
});

const Line334: any = styled('div')({
  border: `1px solid rgba(227, 227, 227, 1)`,
  width: `294px`,
  height: `0px`,
  position: `absolute`,
  left: `4px`,
  top: `300px`,
});

const Image34: any = styled('img')({
  height: `49px`,
  width: `50px`,
  position: `absolute`,
  left: `249px`,
  top: `0px`,
});

const ChickenBbq9: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `119px`,
  top: `219px`,
});

const WithExtraChesse9: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(121, 123, 126, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `118px`,
  top: `246px`,
});

const Q209: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `120px`,
  top: `273px`,
});

const MaskGroup8: any = styled('img')({
  height: `80px`,
  width: `80px`,
  position: `absolute`,
  left: `19px`,
  top: `96px`,
});

const MaskGroup9: any = styled('img')({
  height: `80px`,
  width: `80px`,
  position: `absolute`,
  left: `19px`,
  top: `221px`,
});

const Group1723: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `130px`,
  height: `50px`,
  left: `585px`,
  top: `871px`,
});

const Rectangle174: any = styled('div')({
  border: `1px solid rgba(255, 107, 0, 1)`,
  boxSizing: `border-box`,
  borderRadius: `25px`,
  width: `130px`,
  height: `50px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector8: any = styled('img')({
  height: `16px`,
  width: `16.5px`,
  position: `absolute`,
  left: `22px`,
  top: `17px`,
});

const Vector9: any = styled('img')({
  height: `16px`,
  width: `16.5px`,
  position: `absolute`,
  left: `22px`,
  top: `17px`,
});

const Rejected: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 107, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `48px`,
  top: `17px`,
});

const Group1725: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `341px`,
  height: `411px`,
  left: `397px`,
  top: `91px`,
});

const OrderBox6: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(138, 138, 138, 1)`,
  boxSizing: `border-box`,
  borderRadius: `9px`,
  width: `341px`,
  height: `411px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const OrderPlaced15: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `299px`,
  height: `300px`,
  left: `19px`,
  top: `20px`,
});

const Order11: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Q17May20230530Pm5: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(121, 123, 126, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `27px`,
});

const ChickenBbq10: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `100px`,
  top: `82px`,
});

const WithExtraChesse10: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(121, 123, 126, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `99px`,
  top: `109px`,
});

const Q2010: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `101px`,
  top: `136px`,
});

const Qty111: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `260px`,
  top: `134px`,
});

const Line335: any = styled('div')({
  border: `1px solid rgba(227, 227, 227, 1)`,
  width: `294px`,
  height: `0px`,
  position: `absolute`,
  left: `4px`,
  top: `300px`,
});

const Image35: any = styled('img')({
  height: `49px`,
  width: `50px`,
  position: `absolute`,
  left: `249px`,
  top: `0px`,
});

const ChickenBbq11: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `119px`,
  top: `219px`,
});

const WithExtraChesse11: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(121, 123, 126, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `118px`,
  top: `246px`,
});

const Q2011: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `120px`,
  top: `273px`,
});

const MaskGroup10: any = styled('img')({
  height: `80px`,
  width: `80px`,
  position: `absolute`,
  left: `19px`,
  top: `96px`,
});

const MaskGroup11: any = styled('img')({
  height: `80px`,
  width: `80px`,
  position: `absolute`,
  left: `19px`,
  top: `221px`,
});

const Qty112: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `676px`,
  top: `361px`,
});

const Group1726: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `130px`,
  height: `50px`,
  left: `585px`,
  top: `435px`,
});

const Rectangle175: any = styled('div')({
  border: `1px solid rgba(255, 107, 0, 1)`,
  boxSizing: `border-box`,
  borderRadius: `25px`,
  width: `130px`,
  height: `50px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector81: any = styled('img')({
  height: `16px`,
  width: `16.5px`,
  position: `absolute`,
  left: `22px`,
  top: `17px`,
});

const Vector91: any = styled('img')({
  height: `16px`,
  width: `16.5px`,
  position: `absolute`,
  left: `22px`,
  top: `17px`,
});

const Rejected1: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 107, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `48px`,
  top: `17px`,
});

const Component71: any = styled(Component7)(({ theme }: any) => ({
  width: `1107.56px`,
  height: `51px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

function Component8(props: OrderList): JSX.Element {
  return (
    <Component81 className={props.className}>
      <Component71 />
      <OrderBox1 />
      <OrderPlaced1>
        <Order10>{`Order #10`}</Order10>
        <Q17May20230530Pm>{`17 May 2023, 05:30 PM`}</Q17May20230530Pm>
        <Rectangle17></Rectangle17>
        <Completed>{`COMPLETED`}</Completed>
        <Vector10
          src={`assets/images/Component8_Vector_10.png`}
          loading="lazy"
          alt={'Vector 10'}
        />
        <ChickenBbq>{`Chicken BBQ`}</ChickenBbq>
        <WithExtraChesse>{`With extra chesse`}</WithExtraChesse>
        <Q20>{`$20`}</Q20>
        <Qty1>{`Qty:1`}</Qty1>
        <Line33></Line33>
        <Image3
          src={`assets/images/Component8_image_3.png`}
          loading="lazy"
          alt={'image 3'}
        />
      </OrderPlaced1>
      <ChickenBbq1>{`Chicken BBQ`}</ChickenBbq1>
      <WithExtraChesse1>{`With extra chesse`}</WithExtraChesse1>
      <Q201>{`$20`}</Q201>
      <Qty11>{`Qty: 1`}</Qty11>
      <MaskGroup
        src={`assets/images/Component8_Mask_group.png`}
        loading="lazy"
        alt={'Mask group'}
      />
      <MaskGroup1
        src={`assets/images/Component8_Mask_group_1.png`}
        loading="lazy"
        alt={'Mask group'}
      />
      <Qty12>{`Qty: 1`}</Qty12>
      <Group1719>
        <OrderBox2></OrderBox2>
        <OrderPlaced11>
          <Order12>{`Order #12`}</Order12>
          <Q17May20230530Pm1>{`17 May 2023, 05:30 PM`}</Q17May20230530Pm1>
          <Rectangle171></Rectangle171>
          <Completed1>{`COMPLETED`}</Completed1>
          
          <Vector101
            src={`assets/images/Component8_Vector_10_1.png`}
            loading="lazy"
            alt={'Vector 10'}
          />
          <ChickenBbq2>{`Chicken BBQ`}</ChickenBbq2>
          <WithExtraChesse2>{`With extra chesse`}</WithExtraChesse2>
          <Q202>{`$20`}</Q202>
          <Qty13>{`Qty:1`}</Qty13>
          <Qty14>{`Qty:1`}</Qty14>
          <Line331></Line331>
          <Image31
            src={`assets/images/Component8_image_3_1.png`}
            loading="lazy"
            alt={'image 3'}
          />
        </OrderPlaced11>
        <ChickenBbq3>{`Chicken BBQ`}</ChickenBbq3>
        <WithExtraChesse3>{`With extra chesse`}</WithExtraChesse3>
        <Q203>{`$20`}</Q203>
        <MaskGroup2
          src={`assets/images/Component8_Mask_group_2.png`}
          loading="lazy"
          alt={'Mask group'}
        />
        <MaskGroup3
          src={`assets/images/Component8_Mask_group_3.png`}
          loading="lazy"
          alt={'Mask group'}
        />
      </Group1719>
      <Group1720>
        <OrderBox3></OrderBox3>
        <OrderPlaced12>
          <Order13>{`Order #13`}</Order13>
          <Q17May20230530Pm2>{`17 May 2023, 05:30 PM`}</Q17May20230530Pm2>
          <Rectangle172></Rectangle172>
          <Completed2>{`COMPLETED`}</Completed2>
          <Vector102
            src={`assets/images/Component8_Vector_10_2.png`}
            loading="lazy"
            alt={'Vector 10'}
          />
          <ChickenBbq4>{`Chicken BBQ`}</ChickenBbq4>
          <WithExtraChesse4>{`With extra chesse`}</WithExtraChesse4>
          <Q204>{`$20`}</Q204>
          <Qty15>{`Qty:1`}</Qty15>
          <Line332></Line332>
          <Image32
            src={`assets/images/Component8_image_3_2.png`}
            loading="lazy"
            alt={'image 3'}
          />
        </OrderPlaced12>
        <ChickenBbq5>{`Chicken BBQ`}</ChickenBbq5>
        <WithExtraChesse5>{`With extra chesse`}</WithExtraChesse5>
        <Q205>{`$20`}</Q205>
        <MaskGroup4
          src={`assets/images/Component8_Mask_group_4.png`}
          loading="lazy"
          alt={'Mask group'}
        />
        <MaskGroup5
          src={`assets/images/Component8_Mask_group_5.png`}
          loading="lazy"
          alt={'Mask group'}
        />
      </Group1720>
      <Group1721>
        <OrderBox4></OrderBox4>
        <OrderPlaced13>
          <Order14>{`Order #14`}</Order14>
          <Q17May20230530Pm3>{`17 May 2023, 05:30 PM`}</Q17May20230530Pm3>
          <ChickenBbq6>{`Chicken BBQ`}</ChickenBbq6>
          <WithExtraChesse6>{`With extra chesse`}</WithExtraChesse6>
          <Q206>{`$20`}</Q206>
          <Qty16>{`Qty:1`}</Qty16>
          <Line333></Line333>
          <Image33
            src={`assets/images/Component8_image_3_3.png`}
            loading="lazy"
            alt={'image 3'}
          />
        </OrderPlaced13>
        <ChickenBbq7>{`Chicken BBQ`}</ChickenBbq7>
        <WithExtraChesse7>{`With extra chesse`}</WithExtraChesse7>
        <Q207>{`$20`}</Q207>
        <MaskGroup6
          src={`assets/images/Component8_Mask_group_6.png`}
          loading="lazy"
          alt={'Mask group'}
        />
        <MaskGroup7
          src={`assets/images/Component8_Mask_group_7.png`}
          loading="lazy"
          alt={'Mask group'}
        />
      </Group1721>
      <Qty17>{`Qty:1`}</Qty17>
      <Qty18>{`Qty:1`}</Qty18>
      <Group1722>
        <OrderBox5></OrderBox5>
        <OrderPlaced14>
          <Order15>{`Order #15`}</Order15>
          <Q17May20230530Pm4>{`17 May 2023, 05:30 PM`}</Q17May20230530Pm4>
          <Rectangle173></Rectangle173>
          <Completed3>{`COMPLETED`}</Completed3>
          <Vector103
            src={`assets/images/Component8_Vector_10_3.png`}
            loading="lazy"
            alt={'Vector 10'}
          />
          <ChickenBbq8>{`Chicken BBQ`}</ChickenBbq8>
          <WithExtraChesse8>{`With extra chesse`}</WithExtraChesse8>
          <Q208>{`$20`}</Q208>
          <Qty19>{`Qty:1`}</Qty19>
          <Qty110>{`Qty:1`}</Qty110>
          <Line334></Line334>
          <Image34
            src={`assets/images/Component8_image_3_4.png`}
            loading="lazy"
            alt={'image 3'}
          />
        </OrderPlaced14>
        <ChickenBbq9>{`Chicken BBQ`}</ChickenBbq9>
        <WithExtraChesse9>{`With extra chesse`}</WithExtraChesse9>
        <Q209>{`$20`}</Q209>
        <MaskGroup8
          src={`assets/images/Component8_Mask_group_8.png`}
          loading="lazy"
          alt={'Mask group'}
        />
        <MaskGroup9
          src={`assets/images/Component8_Mask_group_9.png`}
          loading="lazy"
          alt={'Mask group'}
        />
      </Group1722>
      <Group1723>
        <Rectangle174></Rectangle174>
        <Vector8
          src={`assets/images/Component8_Vector_8.png`}
          loading="lazy"
          alt={'Vector 8'}
        />
        <Vector9
          src={`assets/images/Component8_Vector_9.png`}
          loading="lazy"
          alt={'Vector 9'}
        />
        <Rejected>{`REJECTED`}</Rejected>
      </Group1723>
      <Group1725>
        <OrderBox6></OrderBox6>
        <OrderPlaced15>
          <Order11>{`Order #11`}</Order11>
          <Q17May20230530Pm5>{`17 May 2023, 05:30 PM`}</Q17May20230530Pm5>
          <ChickenBbq10>{`Chicken BBQ`}</ChickenBbq10>
          <WithExtraChesse10>{`With extra chesse`}</WithExtraChesse10>
          <Q2010>{`$20`}</Q2010>
          <Qty111>{`Qty:1`}</Qty111>
          <Line335></Line335>
          <Image35
            src={`assets/images/Component8_image_3_5.png`}
            loading="lazy"
            alt={'image 3'}
          />
        </OrderPlaced15>
        <ChickenBbq11>{`Chicken BBQ`}</ChickenBbq11>
        <WithExtraChesse11>{`With extra chesse`}</WithExtraChesse11>
        <Q2011>{`$20`}</Q2011>
        <MaskGroup10
          src={`assets/images/Component8_Mask_group_10.png`}
          loading="lazy"
          alt={'Mask group'}
        />
        <MaskGroup11
          src={`assets/images/Component8_Mask_group_11.png`}
          loading="lazy"
          alt={'Mask group'}
        />
      </Group1725>
      <Qty112>{`Qty:1`}</Qty112>
      <Group1726>
        <Rectangle175></Rectangle175>
        <Vector81
          src={`assets/images/Component8_Vector_8_1.png`}
          loading="lazy"
          alt={'Vector 8'}
        />
        <Vector91
          src={`assets/images/Component8_Vector_9_1.png`}
          loading="lazy"
          alt={'Vector 9'}
        />
        <Rejected1>{`REJECTED`}</Rejected1>
      </Group1726>
      
    </Component81>
  );
}

export default Component8;
