/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import Component7 from './OrderBox';
import CardGridContainer from '../Layouts/GridContainer';
import { FaCheck } from 'react-icons/fa';

function Component8(): JSX.Element {
  return (
    < >
      <Component7 />
      <CardGridContainer grid={4} >
       {Array.from([1,2,3,4,5]).map((el=>{
        return (
          <>
          <div className="p-4 bg-white  rounded-lg shadow-md">
          <div className="flex  justify-between mb-4">
            <div>
              <h2 className="font-bold text-xl">Order #1017</h2>
              <p className="text-gray-500">May 2023, 05:30</p>
            </div>
            <div >
              <img src="assets/images/food-sample.png" alt="Order Image" className="rounded-md"  width={40} height={40}/>
            </div>
          </div>

          <div className="flex justify-between mb-4">
            <div >
              <img src="assets/images/food-sample.png" alt="Order Image" className="rounded-md" width={60} height={60} />
            </div>
            <div className="text-center">
              <div className="flex items-center mb-2">
                <h3 className="text-lg">Order Title</h3>
              </div>
              <p className="text-gray-500">Description</p>
              <p className="font-bold">$25.99</p>
            </div>
            <p>Qty: 1</p>
          </div>
          <div className="flex justify-between mb-4">
            <div >
              <img src="assets/images/food-sample.png" alt="Order Image" className="rounded-md" width={60} height={60} />
            </div>
            <div className="text-center">
              <div className="flex items-center mb-2">
                <h3 className="text-lg">Order Title</h3>
              </div>
              <p className="text-gray-500">Description</p>
              <p className="font-bold">$25.99</p>
            </div>
            <p>Qty: 1</p>
          </div>

          <hr className="my-4 border-gray-300" />

          <div className="flex justify-end">
            <button className="flex items-center border border-green-500 rounded-full px-4 py-2">
              <FaCheck size={20} color='green' className='mr-2' />
              Completed
            </button>
          </div>
        </div>
          </>
        );
       })) 
       }
       
      </CardGridContainer>

    </>
  );
}

export default Component8;
